import type { Product } from '@handshake/contracts';

/** Synthetic-only fixture catalog used by authoritative policy evaluation and WebMCP tools. */
export const SYNTHETIC_CATALOG: readonly Product[] = [
  {
    id: 'harbor-vanity',
    name: 'Harbor vanity',
    category: 'vanity',
    finish: 'matte black',
    priceCents: 248000,
    widthIn: 36,
    depthIn: 21,
    heightIn: 34,
    clearanceIn: 30,
    accessible: true,
    sku: 'SYN-VAN-36-MB',
    mount: 'floor',
    doorSwingIn: 18,
    requiresPlumbing: true,
    requiresElectrical: false,
    requiresVenting: false,
    landingLeftIn: 0,
    landingRightIn: 0,
    counterRun: true,
  },
  {
    id: 'open-shower',
    name: 'Open-entry shower',
    category: 'shower',
    finish: 'clear glass',
    priceCents: 490000,
    widthIn: 42,
    depthIn: 42,
    heightIn: 84,
    clearanceIn: 36,
    accessible: true,
    sku: 'SYN-SHW-42-CG',
    mount: 'floor',
    doorSwingIn: 0,
    requiresPlumbing: true,
    requiresElectrical: false,
    requiresVenting: false,
    landingLeftIn: 0,
    landingRightIn: 0,
    counterRun: false,
  },
  {
    id: 'compact-wc',
    name: 'Compact WC',
    category: 'toilet',
    finish: 'white',
    priceCents: 168000,
    widthIn: 20,
    depthIn: 29,
    heightIn: 30,
    clearanceIn: 30,
    accessible: false,
    sku: 'SYN-TOI-20-WH',
    mount: 'floor',
    doorSwingIn: 0,
    requiresPlumbing: true,
    requiresElectrical: false,
    requiresVenting: false,
    landingLeftIn: 0,
    landingRightIn: 0,
    counterRun: false,
  },
  {
    id: 'linen-tower',
    name: 'Linen tower',
    category: 'storage',
    finish: 'white oak',
    priceCents: 132000,
    widthIn: 18,
    depthIn: 16,
    heightIn: 72,
    clearanceIn: 24,
    accessible: true,
    sku: 'SYN-STR-18-WO',
    mount: 'floor',
    doorSwingIn: 16,
    requiresPlumbing: false,
    requiresElectrical: false,
    requiresVenting: false,
    landingLeftIn: 0,
    landingRightIn: 0,
    counterRun: false,
  },
  {
    id: 'french-door-fridge',
    name: 'Studio French-door refrigerator',
    category: 'refrigerator',
    finish: 'stainless',
    priceCents: 320000,
    widthIn: 36,
    depthIn: 32,
    heightIn: 70,
    clearanceIn: 36,
    accessible: true,
    sku: 'SYN-REF-36-SS',
    mount: 'floor',
    workCenter: 'refrigerator',
    doorSwingIn: 30,
    requiresPlumbing: true,
    requiresElectrical: true,
    requiresVenting: false,
    landingLeftIn: 0,
    landingRightIn: 15,
    counterRun: false,
  },
  {
    id: 'undermount-sink',
    name: 'Undermount kitchen basin',
    category: 'sink',
    finish: 'stainless',
    priceCents: 95000,
    widthIn: 33,
    depthIn: 22,
    heightIn: 10,
    clearanceIn: 36,
    accessible: true,
    sku: 'SYN-SNK-33-SS',
    mount: 'counter',
    workCenter: 'sink',
    doorSwingIn: 0,
    requiresPlumbing: true,
    requiresElectrical: false,
    requiresVenting: false,
    landingLeftIn: 24,
    landingRightIn: 18,
    counterRun: true,
  },
  {
    id: 'pro-gas-range',
    name: 'Pro-style convection range',
    category: 'range',
    finish: 'stainless',
    priceCents: 280000,
    widthIn: 30,
    depthIn: 26,
    heightIn: 36,
    clearanceIn: 40,
    accessible: false,
    sku: 'SYN-RNG-30-SS',
    mount: 'floor',
    workCenter: 'cooktop',
    doorSwingIn: 24,
    requiresPlumbing: false,
    requiresElectrical: true,
    requiresVenting: true,
    landingLeftIn: 15,
    landingRightIn: 12,
    counterRun: false,
  },
  {
    id: 'quiet-dishwasher',
    name: 'Integrated quiet dishwasher',
    category: 'dishwasher',
    finish: 'panel ready',
    priceCents: 145000,
    widthIn: 24,
    depthIn: 24,
    heightIn: 34,
    clearanceIn: 36,
    accessible: true,
    sku: 'SYN-DSH-24-PR',
    mount: 'floor',
    doorSwingIn: 24,
    requiresPlumbing: true,
    requiresElectrical: true,
    requiresVenting: false,
    landingLeftIn: 0,
    landingRightIn: 0,
    counterRun: true,
  },
  {
    id: 'base-drawer-unit',
    name: 'Three-drawer base cabinet',
    category: 'base_cabinet',
    finish: 'natural walnut',
    priceCents: 85000,
    widthIn: 30,
    depthIn: 24,
    heightIn: 34.5,
    clearanceIn: 30,
    accessible: true,
    sku: 'SYN-CAB-30-NW',
    mount: 'floor',
    doorSwingIn: 21,
    requiresPlumbing: false,
    requiresElectrical: false,
    requiresVenting: false,
    landingLeftIn: 0,
    landingRightIn: 0,
    counterRun: true,
  },
  {
    id: 'upper-glass-cabinet',
    name: 'Upper glazed wall cabinet',
    category: 'wall_cabinet',
    finish: 'natural walnut',
    priceCents: 62000,
    widthIn: 30,
    depthIn: 13,
    heightIn: 30,
    clearanceIn: 0,
    accessible: false,
    sku: 'SYN-WCB-30-NW',
    mount: 'wall',
    doorSwingIn: 14,
    requiresPlumbing: false,
    requiresElectrical: false,
    requiresVenting: false,
    landingLeftIn: 0,
    landingRightIn: 0,
    counterRun: false,
  },
  {
    id: 'pantry-tall-cabinet',
    name: 'Pantry tall cabinet',
    category: 'tall_cabinet',
    finish: 'matte slate',
    priceCents: 175000,
    widthIn: 24,
    depthIn: 24,
    heightIn: 84,
    clearanceIn: 36,
    accessible: true,
    sku: 'SYN-TCB-24-MS',
    mount: 'floor',
    doorSwingIn: 24,
    requiresPlumbing: false,
    requiresElectrical: false,
    requiresVenting: false,
    landingLeftIn: 0,
    landingRightIn: 0,
    counterRun: false,
  },
  {
    id: 'induction-cooktop',
    name: 'Four-zone induction cooktop',
    category: 'cooktop',
    finish: 'black ceramic',
    priceCents: 195000,
    widthIn: 30,
    depthIn: 21,
    heightIn: 4,
    clearanceIn: 36,
    accessible: true,
    sku: 'SYN-CKT-30-BC',
    mount: 'counter',
    workCenter: 'cooktop',
    doorSwingIn: 0,
    requiresPlumbing: false,
    requiresElectrical: true,
    requiresVenting: false,
    landingLeftIn: 15,
    landingRightIn: 12,
    counterRun: true,
  },
  {
    id: 'smart-wall-oven',
    name: 'Single convection wall oven',
    category: 'wall_oven',
    finish: 'stainless',
    priceCents: 235000,
    widthIn: 30,
    depthIn: 25,
    heightIn: 29,
    clearanceIn: 36,
    accessible: true,
    sku: 'SYN-OVN-30-SS',
    mount: 'wall',
    doorSwingIn: 22,
    requiresPlumbing: false,
    requiresElectrical: true,
    requiresVenting: false,
    landingLeftIn: 0,
    landingRightIn: 15,
    counterRun: false,
  },
  {
    id: 'canopy-range-hood',
    name: 'Wall-mount canopy range hood',
    category: 'hood',
    finish: 'stainless',
    priceCents: 110000,
    widthIn: 30,
    depthIn: 20,
    heightIn: 24,
    clearanceIn: 0,
    accessible: false,
    sku: 'SYN-HOD-30-SS',
    mount: 'wall',
    doorSwingIn: 0,
    requiresPlumbing: false,
    requiresElectrical: true,
    requiresVenting: true,
    landingLeftIn: 0,
    landingRightIn: 0,
    counterRun: false,
  },
  {
    id: 'prep-island',
    name: 'Kitchen prep island',
    category: 'island',
    finish: 'butcher block',
    priceCents: 210000,
    widthIn: 60,
    depthIn: 36,
    heightIn: 36,
    clearanceIn: 42,
    accessible: true,
    sku: 'SYN-ISL-60-BB',
    mount: 'floor',
    doorSwingIn: 18,
    requiresPlumbing: false,
    requiresElectrical: true,
    requiresVenting: false,
    landingLeftIn: 0,
    landingRightIn: 0,
    counterRun: true,
  },
  {
    id: 'flush-mount-light',
    name: 'Architectural LED flush mount',
    category: 'lighting',
    finish: 'warm brass',
    priceCents: 45000,
    widthIn: 16,
    depthIn: 16,
    heightIn: 4,
    clearanceIn: 0,
    accessible: true,
    sku: 'SYN-LGT-16-WB',
    mount: 'ceiling',
    doorSwingIn: 0,
    requiresPlumbing: false,
    requiresElectrical: true,
    requiresVenting: false,
    landingLeftIn: 0,
    landingRightIn: 0,
    counterRun: false,
  },
];
